# Generated by Django 2.2 on 2020-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_return_due', models.DateField()),
                ('second_return_due', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesActModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_return_due', models.DateField()),
                ('second_return_due', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTaxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_install_due', models.DateField()),
                ('second_install_due', models.DateField()),
                ('third_install_due', models.DateField()),
                ('fourth_install_due', models.DateField()),
                ('tax_return_date', models.DateField()),
                ('tds_return_date', models.DateField()),
            ],
        ),
    ]
