# Generated by Django 2.2 on 2020-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200712_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeservicesmodel',
            name='accounting_activate',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='activeservicesmodel',
            name='companies_activate',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='activeservicesmodel',
            name='gst_tax_activate',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='activeservicesmodel',
            name='income_tax_activate',
            field=models.BooleanField(),
        ),
    ]
